#!/usr/bin/env python3
"""
Measures real representation steering and rewrites content/scenarios.md from the results.

    python scripts/measure_steering.py                      # measure with the tuned settings
    python scripts/measure_steering.py --model <hf-id>      # measure a different model
    python scripts/measure_steering.py --sweep              # re-tune layer and coefficient

Every probability and every continuation the site ships is produced here. The prompts, prefixes,
direction labels and takeaways are authored; nothing else is.
"""

import argparse
import datetime as dt
import json
import platform
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import torch  # noqa: E402

from steering_core import (  # noqa: E402
    ALPHAS,
    REVISIONS,
    STORED_SIGNIFICANT_DIGITS,
    candidate_id,
    identity_check,
    load_model,
    measure_states,
    num_layers,
    separation_score,
    steering_vector,
    to_payload,
)
import transformers  # noqa: E402

from steering_scenarios import SCENARIOS  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MODEL = "Qwen/Qwen2.5-0.5B-Instruct"


def escape_cell(text: str) -> str:
    """A Markdown table cell must stay on one line, and a literal pipe must be escaped."""
    return " ".join(text.split()).replace("\\", "\\\\").replace("|", "\\|")


def render_markdown(payloads, model_id: str, measured_on: str) -> str:
    lines = [
        "# Steering scenarios",
        "",
        "Generated by `scripts/measure_steering.py`. **Do not hand-edit the tables** - the next",
        "measurement run overwrites them. Prompts, prefixes, direction labels and takeaways are",
        "authored and are safe to edit; probabilities and continuations are measured.",
        "",
        "Every number below is the model's actual next-token distribution at the position after the",
        "fixed prefix, and every continuation is what the steered model actually generated with",
        "greedy decoding. See `docs/SCENARIOS.md` for the format and `docs/MEASUREMENT.md` for the",
        "method.",
        "",
        f"Model: {model_id}",
        f"Revision: {REVISIONS.get(model_id, 'main')}",
        "Method: difference of means over contrastive continuations; h' = h + alpha * c * v added "
        "to the residual stream at one decoder layer, at every position, where c is the "
        "per-scenario coefficient",
        f"Measured: {measured_on}",
        "",
        "---",
        "",
    ]

    for payload in payloads:
        ids = []
        for token in payload["candidates"]:
            ids.append(candidate_id(token, ids))

        lines += [
            f"## {payload['id']}",
            "",
            f"Title: {payload['title']}",
            f"Negative label: {payload['negative_label']}",
            f"Positive label: {payload['positive_label']}",
            f"Prompt: {payload['prompt']}",
            f"Prefix: {payload['prefix']}",
            f"Takeaway: {payload['takeaway']}",
            f"Layer: {payload['layer']}",
            f"Coefficient: {payload['scale']}",
            "",
            "| ID | Token |",
            "| --- | --- |",
        ]
        for key, token in zip(ids, payload["candidates"]):
            lines.append(f"| {key} | `{token}` |")

        header = " | ".join(["Alpha", *ids, "Other", "Selected", "Stopped", "Continuation"])
        lines += [
            "",
            f"| {header} |",
            "| " + " | ".join(["---"] * (len(ids) + 5)) + " |",
        ]
        for state in payload["states"]:
            # By index: two candidates can decode to the same string, and a string lookup would
            # silently point at the first of them.
            selected = ids[state["selected_index"]]
            cells = [
                f"{state['alpha']:g}",
                *[f"{value:g}" for value in state["percents"]],
                f"{state['other']:g}",
                selected,
                "limit" if state.get("truncated") else "end",
                escape_cell(state["continuation"]),
            ]
            lines.append("| " + " | ".join(cells) + " |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def sweep(tokenizer, model, spec, layers, scales):
    """Prints a score for each (layer, coefficient) so a new model can be retuned by eye."""
    best = None
    for layer in layers:
        vector = steering_vector(
            tokenizer, model, spec.prompt, spec.prefix,
            spec.negative_examples, spec.positive_examples, layer,
        )
        for scale in scales:
            states = measure_states(
                tokenizer, model, spec.prompt, spec.prefix, vector, layer,
                scale=scale, alphas=(-2.0, 0.0, 2.0), generate=False, top_k=6,
            )
            score = separation_score(states)
            winners = [state.top_tokens[0] for state in states]
            print(
                f"  layer {layer:>2}  coefficient {scale:<4}  score {score['score']:.3f}  "
                f"winners {winners}"
            )
            if best is None or score["score"] > best[0]:
                best = (score["score"], layer, scale)
    print(f"  -> best for {spec.id}: layer {best[1]}, coefficient {best[2]} (score {best[0]:.3f})")
    return best


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--out", default=str(ROOT / "content" / "scenarios.md"))
    parser.add_argument("--report", default=str(ROOT / "docs" / "measurement-report.json"))
    parser.add_argument("--max-new-tokens", type=int, default=40)
    parser.add_argument("--sweep", action="store_true", help="re-tune layer and coefficient")
    parser.add_argument("--device", default="cpu")
    args = parser.parse_args()

    torch.manual_seed(0)
    print(f"loading {args.model} ...")
    tokenizer, model = load_model(args.model, device=args.device)
    depth = num_layers(model)
    print(f"  {depth} layers, hidden size {model.config.hidden_size}")

    if args.sweep:
        layers = sorted({max(1, round(depth * f)) for f in (0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)})
        for spec in SCENARIOS:
            print(f"\n{spec.id}:")
            sweep(tokenizer, model, spec, layers, (0.5, 1.0, 1.5, 2.0))
        print("\nPut the chosen values into scripts/steering_scenarios.py and re-run without --sweep.")
        return 0

    payloads = []
    identity = {}
    for spec in SCENARIOS:
        layer = min(spec.layer, depth)
        print(f"\n{spec.id}: layer {layer}, coefficient {spec.scale}")
        vector = steering_vector(
            tokenizer, model, spec.prompt, spec.prefix,
            spec.negative_examples, spec.positive_examples, layer,
        )
        states = measure_states(
            tokenizer, model, spec.prompt, spec.prefix, vector, layer,
            scale=spec.scale, alphas=ALPHAS, generate=True,
            max_new_tokens=args.max_new_tokens, top_k=512,
        )
        # Does the hook at alpha = 0 actually leave the model alone? Measured, not assumed:
        # the alpha = 0 row is the reference the whole page is read against.
        identity[spec.id] = identity_check(
            tokenizer, model, spec.prompt, spec.prefix, vector, layer, scale=spec.scale
        )
        check = identity[spec.id]
        print(
            f"  identity at alpha={check['neutral_alpha']:g}: "
            f"max|dp| = {check['max_abs_probability_difference']:.3e}, "
            f"continuation matches = {check['continuation_matches_unhooked']}; "
            f"control at alpha={check['control_alpha']:g} detected = {check['control_detected']} "
            f"(max|dp| = {check['control_max_abs_probability_difference']:.3e})"
        )
        if not check["control_detected"]:
            # Without a detected control the zero above is not evidence of anything.
            print("  WARNING: the identity control was not detected; the comparison has no power")

        payload = to_payload(spec, states, layer, spec.scale)
        payloads.append(payload)
        for state in payload["states"]:
            print(f"  a={state['alpha']:+.1f} {state['selected']!r} -> {state['continuation'][:70]}")

    measured_on = dt.date.today().isoformat()
    Path(args.out).write_text(render_markdown(payloads, args.model, measured_on), encoding="utf8")
    print(f"\nwrote {args.out}")

    # Everything needed to challenge a number, recorded from the run rather than asserted in
    # prose. An audit asked for the runtime, device, dtype and decoding configuration to live in
    # the artifact itself; a document can drift from the code, this cannot.
    report = {
        "model": args.model,
        "revision": REVISIONS.get(args.model, "main"),
        "measured": measured_on,
        "layers_total": depth,
        "hidden_size": model.config.hidden_size,
        "alphas": ALPHAS,
        "runtime": {
            "python": platform.python_version(),
            "platform": platform.platform(),
            "machine": platform.machine(),
            "torch": torch.__version__,
            "transformers": transformers.__version__,
            "device": str(model.device),
            "dtype": str(model.dtype),
            "attn_implementation": "eager",
        },
        "decoding": {
            "strategy": "greedy",
            "do_sample": False,
            "num_beams": 1,
            "temperature": None,
            "top_p": None,
            "top_k": None,
            "repetition_penalty": 1.0,
            "max_new_tokens": args.max_new_tokens,
        },
        "intervention": {
            "equation": "h' = h + alpha * c * v",
            "hook": "forward hook on decoder_layers[layer - 1], output is hidden_states[layer]",
            "scope": "every position the forward pass sees, prefill and each decoded position",
            "vector": "mean activation over continuation tokens of positive examples minus "
                      "the same over negative examples; not normalised",
        },
        "probabilities": {
            "softmax_dtype": "float64",
            "source": "full vocabulary row; displayed candidates read out of it by token id",
            "stored_significant_digits": STORED_SIGNIFICANT_DIGITS,
            "other": "1 - sum(candidate probabilities), computed before rounding",
        },
        # Hooked at alpha = 0 against no hook at all, under identical decoding. This is the
        # evidence for calling the alpha = 0 row "the unmodified model".
        "identity_at_zero": identity,
        "scenarios": payloads,
    }
    Path(args.report).write_text(json.dumps(report, indent=2) + "\n", encoding="utf8")
    print(f"wrote {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
